- README.rst
- doc/source/conf.py
- doc/source/contributing.rst
- pyproject.toml
Add link to documentation in pyproject.toml
Update links to repo with the new org name: this isn't necessary as there is a redirect, but the links might as well be correct
> Maintenance - Add docs link

- .github/workflows/ci_cd.yml
Remove deprecated `library-namespace` argument for `build-wheelhouse` action
> CI: Remove namepace arg

- .github/workflows/ci_cd.yml
PRs triggered by dependabot events seem to be failing to upload the coverage artifacts to codecov. This PR skips these steps for jobs triggered by a dependabot event.
I think this change is ok: code coverage should generally be unaffected by a dependency change anyway.
> Skip coverage uploads for dependabot PRs

- .github/labeler.yml
- .github/release.yml
Add a config file for auto-generated release notes.
This completely excludes PRs flagged only as `dependencies`. Any dependency bump in the pyproject.toml is labeled as `maintenance`, so we would still list dependency version bumps, just not updates of the lock file.
I'll add a comment with the autogenerated release notes if we were to release this PR branch (diff with 1.0).
> Add release.yml configuration

- .github/workflows/server_checks.yml
Use the workflow defined in Bomanalytics to skip VM management if there are any active workflows among the workflows listed in the action
> CI - skip vm management if active runs

- .github/workflows/ci_cd.yml
Remove explicit vale version from the workflow definition, which should result in falling back to the default defined in the action
> Remove vale version

- .github/workflows/ci_cd.yml
- .github/workflows/server_checks.yml
- doc/changelog.d/248.changed.md
Closes #224
Use the re-usable ansys doc-build actions, and selectively delete the unneeded artifact if the CI will generate a full docs artifact. Copied the implementation from grantami-jobqueue.
Documentation check will fail until #246 is merged
> Use ansys doc build action

- doc/changelog.d/251.fixed.md
- tests/integration/conftest.py
Closes #242
To avoid tests failing when run concurrently with jobqueue tests, filter out records from the 'Tensile test data' table.
I did initially think about using the 'Restricted Substances' database from bomanalytics, but then we'd be using two separate databases: one for the bulk resolvability checks, and one for checking individual records in different states. This way we leave the RS database alone and confine the record creation to the Training database.
This means our bulk resolvability tests will be operating over ~200 fewer records, but we're still up near 1000 records, so I think it's still a good test.
The coupling between the test templates in jobqueue and the tests here also isn't ideal, but I don't really see an alternative.
> Exclude table with dynamic record count from tests

- doc/changelog.d/256.miscellaneous.md
- doc/source/conf.py
Changes to doc deployment in openapi-common for multiversion support changed the location of the object inventory. Use `/version/stable` in intersphinx config.
> Update openapi-common reference link

- version/1.0/api/connection.html
- version/1.1/api/connection.html
- version/1.2/api/connection.html
- version/stable/api/connection.html
Closes #258 
Replace all instances of `https://openapi.docs.pyansys.com/api` with `https://openapi.docs.pyansys.com/version/stable/api`
> Fix cross-references

- .github/workflows/label.yml
- doc/changelog.d/266.changed.md
Closes #265 
Skips generation of changelog fragments for dependabot PRs
> Don't generate changelog fragments for dependabot PRs

- .github/workflows/label.yml
- doc/changelog.d/260.changed.md
Closes #257 
Previously, if the labels.yml file was updated and merged to main, the entire workflow would run. Now, only the label-syncer job will run. The others will be filtered out by conditionals or dependencies.
> Only run labeler workflow on pull requests

- .github/workflows/label.yml
- doc/changelog.d/307.maintenance.md
Ignore pre-commit-ci PRs for changelog fragment creation.
> Don't create changelog fragments for pre-commit updates

- .github/workflows/ci_cd.yml
- doc/changelog.d/318.maintenance.md
Adds an input to CI workflow to publish builds to the private PyPI.
Publishing after every push to main would be problematic without some kind of automated management of build numbers. We don't anticipate many iterations here and `poetry version` does not yet support bumping dev builds, so this makes it a deliberate action to publish it to the private index.
The build will only be published if the workflow is manually triggered on the main branch and the input explicitly set to true.
> Publish dev builds to private PyPI

- .github/workflows/ci_cd.yml
- doc/changelog.d/320.maintenance.md
Closes #279 
Use trusted publisher approach for release.
> Use PyPI Trusted Publisher approach for releases

- doc/changelog.d/321.documentation.md
- doc/source/api/connection.rst
- doc/source/conf.py
- doc/source/getting_started/index.rst
- doc/styles/config/vocabularies/ANSYS/accept.txt
https://github.com/ansys/pygranta/issues/109
Adds a link to the OpenAPI-Common documentation, to the section that presents supported auth methods in a formatted table.
> Add link to supported authentication schemes

- .github/workflows/server_checks.yml
- doc/changelog.d/324.maintenance.md
When integration tests failed, the job to check whether there are other active workflow runs was skipped and the VM was always turned off.
Adds a condition on the `check_workflow_runs` job to always run, unless the whole workflow has been cancelled, in which case the VM shutdown is also skipped.
> Improve VM management in CI

- doc/changelog.d/337.documentation.md
- doc/source/conf.py
- doc/source/user_guide/index.rst
Closes #336 
Update Ansys doc reference to v251. Changes were required to explicitly link to the index.html page (this may be an artifact of testing against the internal QA site), and linking to the new 'Gateway' help page, instead of for a specific host.
> Update Ansys documentation links to 2025 R1

- doc/changelog.d/340.documentation.md
- doc/source/conf.py
Closes #339 
Use the 2024 R2 public documentation site for core software documentation references.
We have to use the 2024 R2 documentation, because the 2025 R1 documentation will be released *after* this package.
> Use public 2024 R2 Ansys documentation

- README.rst
- doc/changelog.d/351.documentation.md
25R1 did not include changes to the record list API, so this version still only requires a 24R2 MI installation.
> Revert required MI version bump to 2024 R2

- doc/changelog.d/364.maintenance.md
- pyproject.toml
Bump version to 2.0.0.dev1 to be able to publish a build compatible with serverapi 5.0 to the private index.
> Bump version to 2.0.0.dev1

- .github/workflows/server_checks.yml
- doc/changelog.d/377.maintenance.md
PR #374 added tests against MI 2024 R1, but didn't start the machine. CI on that PR passed because the machine was already on.
This PR adds the additional machine to the "Start VM" job.
> Start Granta MI 2024 R1 test machine

- doc/changelog.d/378.fixed.md
- tests/conftest.py
- tests/integration/conftest.py
Improve the error message if integration tests are run and `--mi-version` is not provided
> Handle missing Granta MI version for integration tests

- .github/dependabot.yml
- doc/changelog.d/380.maintenance.md
Azure pypi feeds have an unhelpful extra redirect, we need to add a duplicate entry which has the feed GUID instead of the feed name in order to get dependabot to correctly fetch dependencies.
https://github.com/dependabot/dependabot-core/issues/4780
While we're here let's also add dependency groups as per jobqueue.
> Fix Dependabot Configuration for Private PyPI

- doc/changelog.d/399.maintenance.md
- tests/integration/test_integration.py
These tests are currently failing due to the issue included in the xfail reason.
This PR should be merged to ensure main is passing, and will need to be subsequently reverted once Granta MI is updated.
> Temporarily xfail broken 2025 R2 integration tests

- .github/workflows/ci_cd.yml
- doc/changelog.d/405.maintenance.md
Use PyPI-authored publish action, instead of the Ansys-wrapped version. 
Copied from https://actions.docs.ansys.com/version/stable/migrations/release-pypi-trusted-publisher.html#release-pypi-trusted-publisher
> Use PyPI-authored publish action

- doc/changelog.d/401.documentation.md
- src/ansys/grantami/recordlists/_connection.py
Closes #385 
Clarify that unless a list identifier is specified, the audit log entries returned will be limited to the lists visible to the current user only.
> Clarify audit log search behavior

- doc/changelog.d/399.maintenance.md
- doc/changelog.d/408.maintenance.md
- tests/integration/test_integration.py
This reverts commit e0d193849f4d55cfe95b1c7a8ac80599b7ac47d5.
Manually delete generated changelog entry before merging.
> Revert "Temporarily xfail broken 2025 R2 integration tests (#399)"

- README.rst
- doc/changelog.d/415.documentation.md
Closes #414 
Refer to the improved PyGranta metapackage documentation for guidance on how to determine package compatibility for unsupported Granta MI versions.
The link points to the version table page, which is updated as part of https://github.com/ansys/pygranta/pull/175
> Improve documentation for Granta MI version support

- doc/changelog.d/401.documentation.md
- doc/changelog.d/413.added.md
- src/ansys/grantami/recordlists/_connection.py
- tests/integration/test_integration.py
- tests/test_client.py
- tests/test_connection.py
Closes #412 
Closes #411 
Closes #410 
Convert `RecordListsApiClient` into an abstract class, and create private concrete implementations for each supported Granta MI version. This makes the implementation more explicit, providing a direct mapping between Granta MI version and client class definition. Each class then contains the model and api module as class variables, which are then used to instantiate the class and required APIs.
The abstract class defines all public methods and provides docstrings. It also documents which Granta MI versions are supported for each method.
If a method is implemented for all supported versions, then the 'current' implementation is included in the abstract class. If the implementation is the same for all versions, it can be inherited directly. If the …
> Re-organize ApiClient hierarchy

- .github/workflows/ci_cd.yml
- .github/workflows/dependabot_approve.yml
- .github/workflows/label.yml
- .github/workflows/server_checks.yml
- doc/changelog.d/418.maintenance.md
Closes #419 
All actions are pinned to the latest available version, except for ansys/actions which are pinned to v9.0.9. See https://github.com/ansys/actions/issues/814 for cause.
> Use commit shas to pin action versions

- .github/workflows/ci_cd.yml
- doc/changelog.d/423.maintenance.md
Closes #404 
Adds an extra step to check whether integration checks have successfully run or have been skipped for dependabot PRs.
I've updated required checks to include the new step, the build-library step, and all unit tests steps.
> Add integration checks completeness step at CI top-level
