.github/workflows/ci_cd.yml, .github/workflows/server_checks.yml, README.rst, pyproject.toml
Cherrypick #86 and increase `post` version number.
=> Add test coverage reporting

.github/scripts/check_server.py, .github/workflows/server_checks.yml
Update CI to work with new test server. 
Most commits in this PR were for debugging purposes. The only real change required was to set the user agent to something other than the requests default. The changes remaining though are improvements, and so can be left in.
=> Update CI for new test server

.github/workflows/ci_cd.yml, doc/styles/Vocab/ANSYS/accept.txt
Try incorporating the fix suggested here https://github.com/errata-ai/vale/issues/706#issuecomment-1771748870 to resolve the odd behavior around vale warnings.
=> Fix vale checking

README.rst, doc/source/index.rst
Add version number on docs homepage header
Remove badges from docs homepage 
Add metapackage installation instruction on README and docs (Closes #66)
=> Docs: version and install instructions

pyproject.toml
=> Bump dev release version

src/ansys/grantami/recordlists/_models.py, tests/integration/test_integration.py, tests/test_models.py
=> Allow `match_all` and `match_any` in boolean criterion

src/ansys/grantami/recordlists/_connection.py
Closes #212 
Mark the new method added as part of #165 as added in version 1.2
=> Add versionadded directive

src/ansys/grantami/recordlists/_connection.py, tests/test_item_resolver.py
Closes #218 
Iterate over databases with the expected GUID when resolving items. Exit early if resolved.
=> Resolve items per database

tests/integration/conftest.py, tests/integration/test_integration.py
Closes #209 
The actual issue and fix is in Granta MI, so this PR is just adding some new failing tests which will be resolved with a new build of Granta MI on our test server.
~~Expect CI to fail in this PR until the server is upgraded.~~
Example of failed CI: https://github.com/ansys/grantami-recordlists/actions/runs/8694295314/job/23843233285
Server is updated and CI should now pass.
=> Add additional include_items tests

.github/dependabot.yml, .github/labeler.yml, .github/release.yml, .github/workflows/label.yml
Closes #230 
Use official Github actions to label PRs based on branch name. Add bug fixes to release notes
=> Update labelling workflow

.github/workflows/ci_cd.yml, .github/workflows/server_checks.yml
Use workflow from PyGranta to check for active runs, it will be removed from BoMAnalytics.
=> Use PyGranta workflow to check for active runs

CHANGELOG.md
Closes #226 
Add new features to changelog. Update release date following release
=> Add fixes to changelog

.github/workflows/ci_cd.yml, .github/workflows/label.yml, CHANGELOG.md, doc/changelog.d/243.changed.md, doc/changelog.d/changelog_template.jinja, pyproject.toml
#227 
Add the changelog config as per the migration guide for actions v6
=> CI - Add changelog and deploy-changelog action

doc/changelog.d/253.dependencies.md, poetry.lock
Update openapi-common to v2.0.1
=> Update openapi-common to v2.0.1

.github/workflows/ci_cd.yml, doc/changelog.d/253.dependencies.md, poetry.lock, pyproject.toml
Update version number and classifier.
Cherry-picked #246 to avoid vale failure.
~~Wait for #253 to be merged and cherry-picked before merging.~~
=> Prepare 1.2.0 release

.github/workflows/server_checks.yml
=> Use Release VM

.github/workflows/dependabot_approve.yml, doc/changelog.d/314.maintenance.md, pyproject.toml
Add dependabot and pre-commit approve workflow
Copied from ansys-openapi-common
=> Add dependabot and pre-commit approve workflow

README.rst, doc/changelog.d/322.documentation.md
Fix the command and update the associated statement.
=> Fix installation example for git dependency

AUTHORS, CONTRIBUTORS.md, doc/changelog.d/328.maintenance.md
Closes #326 
Closes #327 
Update wording and rename AUTHORS
Update wording in CONTRIBUTORS.md
=> Update CONTRIBUTORS and AUTHORS to new format

.github/workflows/server_checks.yml, doc/changelog.d/335.maintenance.md
Use production VM for CI on release branch
=> Use Production VM for CI on release branch

doc/changelog.d/350.maintenance.md, pyproject.toml
Update version number on main to v1.4.0.dev0
=> Update version number on main to v1.4.0.dev0

doc/changelog.d/349.maintenance.md, pyproject.toml
Prepare v1.3.0 release
I have previously cherry-picked the following commits onto main:
* ebf5b92b0e31029c6883652c4c98c12dca2b25a3
* 71aea37eae1d47daaf5f4225e3656b4f51e061ff
* 73174ec03341a8ee81d80facc81592af7264e405
* a9307e94414605b4f5aec1aef76ea789ce720172
* 0cd50864e9acded3d99d3fb58702a58c35af6473
* 8c55890cd8ddd728e38575331a695bbb25e10dbd
=> Prepare v1.3.0 release

.pre-commit-config.yaml, doc/changelog.d/362.maintenance.md
Update pre-commit hooks version
=> Update ansys/pre-commit-hooks to 0.5.1

.github/workflows/server_checks.yml, doc/changelog.d/372.maintenance.md
Shutdown all VMs if no other PyGranta CI runs are active.
Required by https://github.com/ansys/pygranta/issues/150 and https://github.com/ansys/grantami-bomanalytics/pull/710. A future PR will extend integration tests to run against the additional servers.
=> Shutdown all VMs

doc/changelog.d/379.dependencies.md, poetry.lock
Update ansys-openapi-common to v2.2.2
=> Update ansys-openapi-common to v2.2.2

doc/changelog.d/390.maintenance.md, pyproject.toml
Bump version to 2.0.0.dev2 for release to private PyPI.
=> Bump version to 2.0.0.dev2

.github/workflows/ci_cd.yml, .pre-commit-config.yaml, doc/changelog.d/402.added.md, poetry.lock, pyproject.toml, src/ansys/grantami/recordlists/_connection.py, src/ansys/grantami/recordlists/_models.py, tests/test_models.py
Closes #376 
Adds mypy as a dev dependency to the project and changes the pre-commit config to use a version of mypy installed in the project venv. Makes the various changes required to get mypy to validate the code with the additional type checking in place. These are all mostly assertion checks which don't affect the runtime behavior, except for one change which I have noted.
=> Perform additional mypy type checking

.github/workflows/ci_cd.yml, doc/changelog.d/406.maintenance.md
Closes #397 
Add attestation provenance generation to wheelhouse and build jobs.
=> Generate provenance attestations

.github/workflows/ci_cd.yml, .github/workflows/server_checks.yml, doc/changelog.d/421.dependencies.md, poetry.lock, pyproject.toml
Remove private PyPI references from CI and pyproject.toml
=> Remove private PyPI references

.github/workflows/server_checks.yml, doc/changelog.d/424.maintenance.md
Add 2025 R2 stable test VM on main branch
=> Add 2025 R2 stable test VM

.github/workflows/server_checks.yml, doc/changelog.d/425.maintenance.md
Move release branch to use 25R2 release VM
Add 25R2 machine (except for machine stop)
Remove dev machine
=> Move release branch to use 25R2 release VM

doc/changelog.d/430.dependencies.md, poetry.lock
Address https://github.com/ansys/grantami-recordlists/security/dependabot/29
=> Update tornado to 6.5

.github/workflows/server_checks.yml, doc/changelog.d/438.fixed.md
Update the VM used to build the documentation
=> Update the VM used to build the documentation

doc/changelog.d/455.miscellaneous.md, poetry.lock
Update all dependencies in lock file
=> Update lock file

SECURITY.md, doc/changelog.d/456.miscellaneous.md
Closes #452 
Add SECURITY.md file
=> Add SECURITY.md file
